export const kText = {
  email: "harits.abdullah19@gmail.com",
  aboutMe:
    "I have experience as a full stack developer but I'm only confident in mobile app development. I have an interest in a career related to Flutter, Go, React Native, and the latest technologies or frameworks. Known as a fast learner and likes to work on projects on time.",
  resume:
    "https://docs.google.com/document/d/1sG-A9ulHr12cY02n_0s_DS6hUrgpGsopaEGPfsZP0uo/edit?usp:sharing",
  resumeDownload:
    "https://docs.google.com/document/d/1sG-A9ulHr12cY02n_0s_DS6hUrgpGsopaEGPfsZP0uo/export?format:pdf",
  linkedIn: "https://linkedin.com/in/abd-harits",
  instagram: "https://instagram.com/abd.harits19",
  github: "https://github.com/Harits19",
  medium: "https://harits-abdullah19.medium.com",
  googlePlay: "https://play.google.com/store/apps/developer?id:Abdullah+Harits",
  abdullahHarits: "Abdullah Harits",
  listOfSkill: [
    "Flutter",
    "React Native",
    "Object Oriented Programming",
    "MongoDB",
    "MySQL",
    "CI/CD",
    "GIT",
    "Functional Programming",
    "Go",
    "Mobile Application Developer",
  ],

  projects: [
    {
      image: "ayolunas.png",
      name: "AyoLunas",
      link: "",
      description: "ayolunas_desc",
      highlight: ["Flutter"],
    },
    {
      image: "soundfren.webp",
      name: "Soundfren",
      description: "soundfren_desc",
      link: "https://play.google.com/store/apps/details?id=com.amoeba.soundfren",
      highlight: ["React Native"],
    },
    {
      image: "pejuang.webp",
      name: "Pejuang",
      link: "https://play.google.com/store/apps/details?id=com.bdn.pejuang",
      description: "pejuang_desc",
      highlight: ["React Native"],
    },
    {
      image: "batumbu.png",
      name: "Batumbu",
      description: "batumbu_desc",
      link: "",
      highlight: ["Flutter"],
    },
    {
      image: "protect.webp",
      name: "Protect",
      description: "protect_desc",
      link: "https://play.google.com/store/apps/details?id=com.my_password_app",
      highlight: ["Flutter"],
    },
    {
      image: "primasaver.png",
      name: "Primasaver",
      description: "primasaver_desc",
      link: "https://primasaver.com/home",
      highlight: ["Flutter", "Go", "MongoDB"],
    },
    {
      image: "prayer_time.webp",
      name: "Prayer Time",
      link: "https://play.google.com/store/apps/details?id=com.prayer_time",
      description: "prayer_time_desc",
      highlight: ["Flutter"],
      github: "https://github.com/Harits19/prayer_time_app",
    },
  ],
};
